# Generated by Django 3.1.4 on 2020-12-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201217_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.FileField(upload_to='uploads/audio')),
                ('text', models.CharField(blank=True, default='audio text', max_length=5000)),
            ],
            options={
                'db_table': 'audio',
            },
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='image_name',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
